#!/usr/bin/env python3
"""Local retrieval-augmented question answering over the Lexis Mollis corpus.

Retrieval is entirely local and free: it reuses the embeddings/FAISS index
already built by `pdfkb similarity build` (sentence-transformers/LaBSE,
no API calls) plus the knowledge graph already built by `pdfkb graph build`
to pull in related documents and entities for each retrieved passage. Only
the final answer is generated by an LLM — by default the free "Big Pickle"
model on OpenCode Zen (https://opencode.ai/zen/), an OpenAI-compatible API.

Setup for the LLM step (skip with --no-llm to only use retrieval, for free
with no account at all):
  1. Sign in at https://opencode.ai/zen/ and copy an API key. Note the docs
     ask for billing details even to use free models — check current terms
     before proceeding, this script never touches payment info itself.
  2. export OPENCODE_API_KEY=...
Any other OpenAI-compatible endpoint works too via --api-url/--api-model
(or RAG_API_URL/RAG_API_MODEL env vars), e.g. a local Ollama server.

Examples:
  .venv/bin/python scripts/rag_ask.py "Quels traités mentionnent la Roumanie ?"
  .venv/bin/python scripts/rag_ask.py --no-llm "citoyenneté"   # retrieval only
  .venv/bin/python scripts/rag_ask.py                          # interactive
"""

from __future__ import annotations

import os

# Must be set before faiss/torch touch OpenMP: on macOS, faiss's and
# sentence-transformers' (torch) bundled OpenMP runtimes are two separate
# copies, which OpenMP aborts on by default. This is the documented,
# widely-used (if "unsupported") workaround; combined with pinning faiss to
# one thread below, it's stable in practice.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import argparse
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from pdfkb.similarity.io import read_parquet_records  # noqa: E402

DEFAULT_SIMILARITY_DIR = Path("outputs_v2/similarity")
DEFAULT_RELEASE_DIR = Path("outputs_v2/release")
DEFAULT_GRAPH_DIR = Path("outputs_v2/graph")
DEFAULT_EMBEDDING_MODEL = "sentence-transformers/LaBSE"
DEFAULT_API_URL = "https://opencode.ai/zen/v1/chat/completions"
DEFAULT_API_MODEL = "big-pickle"
DOC_EDGE_TYPES = {"similar_to", "translation", "same_instrument_as"}

SYSTEM_PROMPT = (
    "Tu es un assistant de recherche qui répond STRICTEMENT à partir des extraits de documents "
    "fournis (corpus de traités et instruments juridiques Lexis Mollis, OCR historique, parfois "
    "imparfait). Si l'information n'est pas dans le contexte fourni, dis-le clairement plutôt que "
    "d'inventer. Cite systématiquement l'identifiant de document entre crochets (ex. [16460004_s1]) "
    "et la page quand c'est pertinent. Réponds dans la langue de la question."
)


def _normalise(vectors: np.ndarray) -> np.ndarray:
    vectors = np.asarray(vectors, dtype=np.float32)
    if vectors.ndim == 1:
        vectors = vectors.reshape(1, -1)
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return vectors / norms


class KnowledgeBase:
    """In-memory view over the already-built similarity index and graph."""

    def __init__(
        self,
        similarity_dir: Path = DEFAULT_SIMILARITY_DIR,
        release_dir: Path = DEFAULT_RELEASE_DIR,
        graph_dir: Path = DEFAULT_GRAPH_DIR,
        embedding_model: str = DEFAULT_EMBEDDING_MODEL,
    ) -> None:
        import faiss

        # faiss's and torch's bundled OpenMP runtimes crash (segfault) if faiss
        # is left multi-threaded in the same process as sentence-transformers
        # on macOS — pin faiss to one thread rather than relying on env vars
        # the caller might not have set.
        faiss.omp_set_num_threads(1)

        self.embedding_model_name = embedding_model
        self._model: Any = None

        self.index = faiss.read_index(str(Path(similarity_dir) / "faiss.index"))
        id_map = read_parquet_records(Path(similarity_dir) / "id_map.parquet")
        self.row_to_chunk_id = {int(row["row_index"]): row["chunk_id"] for row in id_map}

        self.chunks_by_id = {c["chunk_id"]: c for c in read_parquet_records(Path(release_dir) / "chunks")}
        self.documents_by_id = {d["document_id"]: d for d in read_parquet_records(Path(release_dir) / "documents")}

        self.doc_edges: dict[str, list[dict]] = defaultdict(list)
        for edge in read_parquet_records(Path(release_dir) / "edges"):
            if (
                edge.get("level") == "document"
                and edge.get("type") in DOC_EDGE_TYPES
                and str(edge.get("src", "")).startswith("doc:")
                and str(edge.get("dst", "")).startswith("doc:")
            ):
                self.doc_edges[edge["src"]].append(edge)

        self.mentions_by_doc: dict[str, list[dict]] = defaultdict(list)
        for mention in read_parquet_records(Path(graph_dir) / "mention_links.parquet"):
            self.mentions_by_doc[mention["document_id"]].append(mention)
        self.nodes_by_id = {n["node_id"]: n for n in read_parquet_records(Path(graph_dir) / "nodes.parquet")}

    def _embed_query(self, text: str) -> np.ndarray:
        if self._model is None:
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(self.embedding_model_name)
        vector = self._model.encode([text], normalize_embeddings=True)
        return _normalise(np.asarray(vector, dtype=np.float32))

    def search(self, query: str, k: int = 8) -> list[dict]:
        query_vector = self._embed_query(query)
        scores, indices = self.index.search(query_vector, k)
        hits = []
        for score, row in zip(scores[0], indices[0], strict=True):
            if row < 0:
                continue
            chunk = self.chunks_by_id.get(self.row_to_chunk_id.get(int(row)))
            if chunk is not None:
                hits.append({"score": float(score), "chunk": chunk})
        return hits

    def entities_for_document(self, document_id: str, limit: int = 6) -> list[dict]:
        rows = sorted(self.mentions_by_doc.get(document_id, []), key=lambda r: r.get("confidence") or 0, reverse=True)
        seen: dict[str, dict] = {}
        for mention in rows:
            node = self.nodes_by_id.get(mention["node_id"])
            if node is None or node["node_id"] in seen:
                continue
            seen[node["node_id"]] = node
            if len(seen) >= limit:
                break
        return list(seen.values())

    def related_documents(self, document_id: str, limit: int = 4) -> list[dict]:
        edges = sorted(
            self.doc_edges.get(f"doc:{document_id}", []),
            key=lambda e: e.get("combined") or e.get("quality_weight") or 0,
            reverse=True,
        )
        related, seen = [], set()
        for edge in edges:
            dst_id = str(edge["dst"])[len("doc:") :]
            if dst_id in seen or dst_id == document_id:
                continue
            seen.add(dst_id)
            doc = self.documents_by_id.get(dst_id)
            if doc is not None:
                related.append({"document": doc, "type": edge["type"], "score": edge.get("combined") or edge.get("quality_weight")})
            if len(related) >= limit:
                break
        return related

    def build_context(self, query: str, k: int = 8, use_graph: bool = True) -> tuple[str, list[dict]]:
        hits = self.search(query, k=k)
        blocks, seen_docs = [], set()
        for hit in hits:
            chunk = hit["chunk"]
            doc = self.documents_by_id.get(chunk["document_id"], {})
            lines = [
                f"### [{chunk['document_id']}] {chunk.get('title') or doc.get('title') or chunk['document_id']} "
                f"(p.{chunk.get('page_number')}, score={hit['score']:.2f})",
                f"Traité : {chunk.get('treaty_id') or 'n/a'} · Année : {chunk.get('year') or 'n/a'} · "
                f"Type : {chunk.get('doc_type') or 'n/a'}",
                "",
                (chunk.get("text") or "").strip(),
            ]
            if use_graph and chunk["document_id"] not in seen_docs:
                seen_docs.add(chunk["document_id"])
                entities = self.entities_for_document(chunk["document_id"])
                if entities:
                    lines += ["", "Entités liées : " + ", ".join(f"{n['label']} ({n['type']})" for n in entities)]
                related = self.related_documents(chunk["document_id"])
                if related:
                    rel_str = "; ".join(
                        f"{r['document'].get('title') or r['document']['document_id']} "
                        f"[{r['document']['document_id']}] ({r['type']})"
                        for r in related
                    )
                    lines += [f"Documents liés : {rel_str}"]
            blocks.append("\n".join(lines))
        return "\n\n---\n\n".join(blocks), hits


def ask_llm(question: str, context: str, api_url: str, api_model: str, api_key: str, timeout: float = 60) -> str:
    import requests

    payload = {
        "model": api_model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Contexte :\n\n{context}\n\n---\n\nQuestion : {question}"},
        ],
        "temperature": 0.2,
    }
    response = requests.post(
        api_url,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("query", nargs="?", help="Question. Omit for interactive mode.")
    parser.add_argument("--k", type=int, default=8, help="Number of chunks to retrieve.")
    parser.add_argument("--no-graph", action="store_true", help="Disable knowledge-graph context expansion.")
    parser.add_argument("--no-llm", action="store_true", help="Print retrieved context only, skip the LLM call.")
    parser.add_argument("--api-url", default=os.environ.get("RAG_API_URL", DEFAULT_API_URL))
    parser.add_argument("--api-model", default=os.environ.get("RAG_API_MODEL", DEFAULT_API_MODEL))
    parser.add_argument("--similarity-dir", type=Path, default=DEFAULT_SIMILARITY_DIR)
    parser.add_argument("--release-dir", type=Path, default=DEFAULT_RELEASE_DIR)
    parser.add_argument("--graph-dir", type=Path, default=DEFAULT_GRAPH_DIR)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    kb = KnowledgeBase(args.similarity_dir, args.release_dir, args.graph_dir)

    def handle(question: str) -> None:
        context, hits = kb.build_context(question, k=args.k, use_graph=not args.no_graph)
        print(f"[{len(hits)} extraits récupérés]", file=sys.stderr)

        if args.no_llm:
            print(context)
            return

        api_key = os.environ.get("OPENCODE_API_KEY")
        if not api_key:
            print(
                "OPENCODE_API_KEY n'est pas défini (voir l'en-tête de scripts/rag_ask.py) — "
                "affichage du contexte brut uniquement.",
                file=sys.stderr,
            )
            print(context)
            return

        try:
            answer = ask_llm(question, context, args.api_url, args.api_model, api_key)
        except Exception as exc:  # noqa: BLE001 - report and fall back, don't crash a REPL
            print(f"Échec de l'appel LLM ({exc}) — affichage du contexte brut à la place.", file=sys.stderr)
            print(context)
            return
        print(answer)
        print("\nSources :", file=sys.stderr)
        for hit in hits:
            chunk = hit["chunk"]
            print(f"  - [{chunk['document_id']}] p.{chunk.get('page_number')} (score {hit['score']:.2f})", file=sys.stderr)

    if args.query:
        handle(args.query)
        return 0

    print("Mode interactif — Ctrl+D ou 'exit' pour quitter.", file=sys.stderr)
    while True:
        try:
            question = input("\n> ").strip()
        except EOFError:
            break
        if not question or question.lower() in {"exit", "quit"}:
            break
        handle(question)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
