#!/usr/bin/env python3
"""Local retrieval-augmented question answering over the Lexis Mollis corpus.

Retrieval is entirely local and free: it reuses the embeddings/FAISS index
already built by `pdfkb similarity build` (sentence-transformers/LaBSE,
no API calls) plus the knowledge graph already built by `pdfkb graph build`
to pull in related documents and entities for each retrieved passage. Only
the final answer is generated by an LLM — by default the free "Big Pickle"
model on OpenCode Zen (https://opencode.ai/zen/), an OpenAI-compatible API.
Run `curl https://opencode.ai/zen/v1/models` for the current list of free
("-free" suffixed) and paid model ids.

Setup for the LLM step (skip with --no-llm to only use retrieval, for free
with no account at all):
  1. Sign in at https://opencode.ai/zen/ and copy an API key. Note the docs
     ask for billing details even to use free models — check current terms
     before proceeding, this script never touches payment info itself.
  2. export OPENCODE_API_KEY=...
Any other OpenAI-compatible endpoint works too via --api-url/--api-model
(or RAG_API_URL/RAG_API_MODEL env vars), e.g. a local Ollama server.

Comparison questions ("compare les types de documents (traité, accord,
déclaration) et dis-moi s'il y a des différences de forme/rédaction") are
detected automatically: if a question names two or more known `doc_type`
labels, the context is built differently from a plain question — it is
prepended with the corpus-wide structural profile of each named type
(`outputs_v2/similarity/doc_type_profiles.json`, built by `pdfkb similarity
build` / `scripts/build_doc_type_profiles.py`: fraction of documents with a
"pleins pouvoirs" preamble, numbered articles, "En foi de quoi" signature
clause, etc.) plus a few real excerpts retrieved *per type* rather than one
undifferentiated top-k search — see `KnowledgeBase.detect_comparison_types`
and `KnowledgeBase.build_context`. This is what lets a small free model
answer precisely instead of guessing from 6-8 semantically-nearest chunks
that may all happen to come from the same type.

Examples:
  .venv/bin/python scripts/rag_ask.py "Quels traités mentionnent la Roumanie ?"
  .venv/bin/python scripts/rag_ask.py "Compare les types de documents (traité, accord, déclaration) et dis-moi s'il y a des différences de forme/rédaction"
  .venv/bin/python scripts/rag_ask.py --no-llm "citoyenneté"   # retrieval only
  .venv/bin/python scripts/rag_ask.py                          # interactive
"""

from __future__ import annotations

import os

# Must be set before faiss/torch touch OpenMP: on macOS, faiss's and
# sentence-transformers' (torch) bundled OpenMP runtimes are two separate
# copies, which OpenMP aborts on by default. This is the documented,
# widely-used (if "unsupported") workaround; combined with pinning faiss to
# one thread below, it's stable in practice.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import argparse
import json
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from pdfkb.prompts import RAG_SYSTEM_PROMPT
from pdfkb.similarity.doc_type_profiles import load_doc_type_mapping
from pdfkb.similarity.io import read_parquet_records
from pdfkb.similarity.lexical import normalise_lexical

DEFAULT_SIMILARITY_DIR = Path("outputs_v2/similarity")
DEFAULT_RELEASE_DIR = Path("outputs_v2/release")
DEFAULT_GRAPH_DIR = Path("outputs_v2/graph")
DEFAULT_DOC_TYPE_MAPPING = Path("metadata_design/doc_type_mapping.json")
DEFAULT_EMBEDDING_MODEL = "sentence-transformers/LaBSE"
DEFAULT_API_URL = "https://opencode.ai/zen/v1/chat/completions"
DEFAULT_API_MODEL = "big-pickle"
DOC_EDGE_TYPES = {"similar_to", "translation", "same_instrument_as"}


def _label_variants(label: str) -> set[str]:
    """Normalised singular/plural forms of a doc_type label for substring matching
    against a normalised question (see `normalise_lexical`: lowercase, no accents,
    punctuation collapsed to single spaces)."""
    norm = normalise_lexical(label)
    if not norm:
        return set()
    variants = {norm}
    words = norm.split()
    if not norm.endswith("s"):
        variants.add(norm + "s")
    if len(words) > 1 and not words[-1].endswith("s"):
        variants.add(" ".join([*words[:-1], words[-1] + "s"]))
    return variants


def detect_doc_types(query: str, labels: list[str]) -> list[str]:
    """Return the known doc_type labels named in `query` (order-preserving, no dupes)."""
    padded_query = f" {normalise_lexical(query)} "
    return [label for label in labels if any(f" {variant} " in padded_query for variant in _label_variants(label))]


def has_comparison_intent(query: str) -> bool:
    """Loose heuristic: does this question sound like it wants to compare document
    types at all? False positives just trigger an unnecessary but harmless
    clarification; false negatives are the real risk -- see
    unmatched_type_clarification, mirrors platform/site/worker/ask.ts's
    hasComparisonIntent."""
    normalised = normalise_lexical(query)
    return any(needle in normalised for needle in ("compar", "differenc", "distinction"))


def unmatched_type_clarification(query: str, compare_types: list[str], doc_type_profiles: dict[str, Any]) -> str | None:
    """When a question clearly wants a type-vs-type comparison but fewer than 2 of
    the named terms match the corpus's actual controlled doc_type vocabulary
    (e.g. asking to compare "Traité" and "Memorandum", the latter not being one of
    the corpus's real labels), answer deterministically instead of leaving it to
    the LLM to notice and explain -- it *can* do that correctly, but
    inconsistently and without ever stating what the real options are."""
    if len(compare_types) >= 2 or not has_comparison_intent(query):
        return None

    available = ", ".join(
        f"{profile['label']} ({profile['n_documents']})"
        for profile in sorted(doc_type_profiles.values(), key=lambda p: p.get("n_documents") or 0, reverse=True)
        if profile.get("label") and profile.get("n_documents")
    )
    matched_note = (
        f"Type reconnu dans votre question : « {compare_types[0]} ». Le ou les autres termes utilisés ne "
        "correspondent à aucun type du corpus. "
        if compare_types
        else "Aucun des termes utilisés ne correspond à un type reconnu du corpus. "
    )
    return (
        "Votre question semble demander une comparaison entre types de documents, mais elle ne peut pas être "
        f"traitée telle quelle : {matched_note}Cette classification (indépendante de cette question) ne connaît "
        f"que les types suivants, avec leur nombre de documents dans le corpus : {available}. Reformulez votre "
        "question en citant deux de ces types exacts, par exemple : « Compare les types Traité et Accord et "
        "dis-moi s'il y a des différences de forme/rédaction »."
    )


def build_degraded_notice(compare_types: list[str], doc_type_profiles: dict[str, Any]) -> str:
    """Companion to unmatched_type_clarification, for the case where we DON'T want
    to refuse outright: compare_types has 0 or 1 real matches but there's still a
    genuine comparison intent. Rather than hard-stopping, `handle()` now falls
    through to a "degraded compare" (free-text search standing in for the
    unmatched term(s), no corpus-wide stats attached) and uses this text as a
    context block telling the LLM exactly how to caveat that part of the answer.
    Mirrors platform/site/worker/ask.ts's buildDegradedNotice."""
    available = ", ".join(
        f"{profile['label']} ({profile['n_documents']})"
        for profile in sorted(doc_type_profiles.values(), key=lambda p: p.get("n_documents") or 0, reverse=True)
        if profile.get("label") and profile.get("n_documents")
    )
    subject = (
        f"« {compare_types[0]} » est un type reconnu du corpus (statistiques ci-dessous). L'autre terme "
        "utilisé dans votre question"
        if compare_types
        else "Aucun des termes utilisés dans votre question"
    )
    return (
        f"### Note méthodologique (à respecter strictement dans ta réponse)\n\n{subject} ne correspond à aucun "
        "des types officiels du corpus. Les extraits montrés pour ce terme proviennent d'une recherche libre "
        "sur le texte/titre des documents, pas d'une catégorie auditée : aucune statistique de pourcentage "
        "n'existe pour cette partie de la comparaison, seulement les exemples concrets cités. Types officiels "
        f"disponibles avec leur nombre de documents dans le corpus : {available}."
    )


def _normalise(vectors: np.ndarray) -> np.ndarray:
    vectors = np.asarray(vectors, dtype=np.float32)
    if vectors.ndim == 1:
        vectors = vectors.reshape(1, -1)
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return vectors / norms


class KnowledgeBase:
    """In-memory view over the already-built similarity index and graph."""

    def __init__(
        self,
        similarity_dir: Path = DEFAULT_SIMILARITY_DIR,
        release_dir: Path = DEFAULT_RELEASE_DIR,
        graph_dir: Path = DEFAULT_GRAPH_DIR,
        embedding_model: str = DEFAULT_EMBEDDING_MODEL,
        doc_type_profiles_path: Path = DEFAULT_SIMILARITY_DIR / "doc_type_profiles.json",
        doc_type_mapping_path: Path = DEFAULT_DOC_TYPE_MAPPING,
    ) -> None:
        import faiss

        # faiss's and torch's bundled OpenMP runtimes crash (segfault) if faiss
        # is left multi-threaded in the same process as sentence-transformers
        # on macOS — pin faiss to one thread rather than relying on env vars
        # the caller might not have set.
        faiss.omp_set_num_threads(1)

        self.embedding_model_name = embedding_model
        self._model: Any = None

        self.index = faiss.read_index(str(Path(similarity_dir) / "faiss.index"))
        id_map = read_parquet_records(Path(similarity_dir) / "id_map.parquet")
        self.row_to_chunk_id = {int(row["row_index"]): row["chunk_id"] for row in id_map}

        self.chunks_by_id = {c["chunk_id"]: c for c in read_parquet_records(Path(release_dir) / "chunks")}
        self.documents_by_id = {d["document_id"]: d for d in read_parquet_records(Path(release_dir) / "documents")}
        # One entry per document, chunks sorted by page — lets build_context
        # pick "the" representative chunk for any document of a named type
        # without a full scan of chunks_by_id per document.
        self.chunks_by_doc: dict[str, list[dict]] = defaultdict(list)
        for chunk in self.chunks_by_id.values():
            self.chunks_by_doc[chunk["document_id"]].append(chunk)
        for doc_chunks in self.chunks_by_doc.values():
            doc_chunks.sort(key=lambda c: c.get("page_number") or 0)

        self.doc_edges: dict[str, list[dict]] = defaultdict(list)
        for edge in read_parquet_records(Path(release_dir) / "edges"):
            if (
                edge.get("level") == "document"
                and edge.get("type") in DOC_EDGE_TYPES
                and str(edge.get("src", "")).startswith("doc:")
                and str(edge.get("dst", "")).startswith("doc:")
            ):
                self.doc_edges[edge["src"]].append(edge)

        self.mentions_by_doc: dict[str, list[dict]] = defaultdict(list)
        for mention in read_parquet_records(Path(graph_dir) / "mention_links.parquet"):
            self.mentions_by_doc[mention["document_id"]].append(mention)
        self.nodes_by_id = {n["node_id"]: n for n in read_parquet_records(Path(graph_dir) / "nodes.parquet")}

        # Optional: doc_type structural profiles (see pdfkb/similarity/doc_type_profiles.py).
        # Absent on older builds — comparison-mode retrieval degrades gracefully to plain
        # top-k search in that case (see `detect_comparison_types`/`build_context`).
        self.doc_type_profiles: dict[str, Any] = {}
        profiles_path = Path(doc_type_profiles_path)
        if profiles_path.exists():
            self.doc_type_profiles = json.loads(profiles_path.read_text(encoding="utf-8")).get("types", {})
        self.doc_type_labels = sorted(load_doc_type_mapping(Path(doc_type_mapping_path)).keys()) or sorted(
            self.doc_type_profiles.keys()
        )

    def _embed_query(self, text: str) -> np.ndarray:
        if self._model is None:
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(self.embedding_model_name)
        vector = self._model.encode([text], normalize_embeddings=True)
        return _normalise(np.asarray(vector, dtype=np.float32))

    def search(self, query: str, k: int = 8) -> list[dict]:
        query_vector = self._embed_query(query)
        scores, indices = self.index.search(query_vector, k)
        hits = []
        for score, row in zip(scores[0], indices[0], strict=True):
            if row < 0:
                continue
            chunk = self.chunks_by_id.get(self.row_to_chunk_id.get(int(row)))
            if chunk is not None:
                hits.append({"score": float(score), "chunk": chunk})
        return hits

    def entities_for_document(self, document_id: str, limit: int = 6) -> list[dict]:
        rows = sorted(self.mentions_by_doc.get(document_id, []), key=lambda r: r.get("confidence") or 0, reverse=True)
        seen: dict[str, dict] = {}
        for mention in rows:
            node = self.nodes_by_id.get(mention["node_id"])
            if node is None or node["node_id"] in seen:
                continue
            seen[node["node_id"]] = node
            if len(seen) >= limit:
                break
        return list(seen.values())

    def related_documents(self, document_id: str, limit: int = 4) -> list[dict]:
        edges = sorted(
            self.doc_edges.get(f"doc:{document_id}", []),
            key=lambda e: e.get("combined") or e.get("quality_weight") or 0,
            reverse=True,
        )
        related, seen = [], set()
        for edge in edges:
            dst_id = str(edge["dst"])[len("doc:") :]
            if dst_id in seen or dst_id == document_id:
                continue
            seen.add(dst_id)
            doc = self.documents_by_id.get(dst_id)
            if doc is not None:
                related.append(
                    {"document": doc, "type": edge["type"], "score": edge.get("combined") or edge.get("quality_weight")}
                )
            if len(related) >= limit:
                break
        return related

    def detect_comparison_types(self, query: str) -> list[str]:
        """Doc_type labels named in `query`, restricted to types we have profiles for.
        `build_context` gives type-restricted retrieval + a real profile block to ANY
        named type, whether there's one (a descriptive question, e.g. "quelles sont
        les caractéristiques d'un memorandum ?") or several (an explicit comparison) --
        a single named type used to fall through to plain whole-corpus search, which
        could surface documents unrelated to the type actually asked about."""
        matched = detect_doc_types(query, self.doc_type_labels)
        return [label for label in matched if label in self.doc_type_profiles] or matched

    def doc_type_profile_block(self, label: str) -> str | None:
        profile = self.doc_type_profiles.get(label)
        if not profile:
            return None
        lines = [
            f"### Profil du type documentaire « {label} » "
            f"({profile.get('instrument_type', 'n/a')}, force juridique={profile.get('legal_force', 'n/a')})",
            profile.get("narrative_fr") or "",
        ]
        openings = profile.get("sample_openings") or []
        if openings:
            lines += ["", "Exemples réels (débuts de document) :"]
            for sample in openings[:3]:
                lines.append(
                    f"- [{sample.get('document_id')}] ({sample.get('year') or 'n/a'}) : « {sample.get('excerpt')} »"
                )
        return "\n".join(lines)

    def hit_block(self, hit: dict, use_graph: bool, seen_docs: set[str]) -> str:
        chunk = hit["chunk"]
        doc = self.documents_by_id.get(chunk["document_id"], {})
        lines = [
            f"### [{chunk['document_id']}] {chunk.get('title') or doc.get('title') or chunk['document_id']} "
            f"(p.{chunk.get('page_number')}, score={hit['score']:.2f})",
            f"Traité : {chunk.get('treaty_id') or 'n/a'} · Année : {chunk.get('year') or 'n/a'} · "
            f"Type : {chunk.get('doc_type') or 'n/a'}",
            "",
            (chunk.get("text") or "").strip(),
        ]
        if use_graph and chunk["document_id"] not in seen_docs:
            seen_docs.add(chunk["document_id"])
            entities = self.entities_for_document(chunk["document_id"])
            if entities:
                lines += ["", "Entités liées : " + ", ".join(f"{n['label']} ({n['type']})" for n in entities)]
            related = self.related_documents(chunk["document_id"])
            if related:
                rel_str = "; ".join(
                    f"{r['document'].get('title') or r['document']['document_id']} "
                    f"[{r['document']['document_id']}] ({r['type']})"
                    for r in related
                )
                lines += [f"Documents liés : {rel_str}"]
        return "\n".join(lines)

    def search_by_doc_type(self, query: str, doc_type: str, k: int, pool_k: int = 150) -> list[dict]:
        """Like `search`, but restricted to chunks whose `doc_type` matches — a plain
        top-k search over the whole corpus can easily miss an under-represented type
        entirely (e.g. 152 « Déclaration » docs vs 807 « Autre »), which is exactly
        wrong for a question that asks to compare types."""
        pool = self.search(query, k=max(pool_k, k))
        matching = [hit for hit in pool if hit["chunk"].get("doc_type") == doc_type]
        return matching[:k]

    def all_hits_for_doc_type(self, query: str, doc_type: str) -> list[dict]:
        """One hit per document of `doc_type` — every document, no cap (see
        platform/site/worker/ask.ts's matching change for why: a purely
        descriptive question has no keywords to meaningfully rank documents
        by, so a fixed top-k sample would drop documents arbitrarily rather
        than meaningfully). Prefers whatever chunk the keyword search actually
        ranked highest for a document (a better excerpt pick within a
        multi-page document); any document of this type the search didn't
        surface at all still gets included, via its first chunk."""
        doc_ids = [doc_id for doc_id, doc in self.documents_by_id.items() if doc.get("doc_type") == doc_type]
        seen_docs: set[str] = set()
        hits: list[dict] = []
        pool = self.search(query, k=max(len(doc_ids) * 3, 50))
        for hit in pool:
            doc_id = hit["chunk"]["document_id"]
            if doc_id in seen_docs or hit["chunk"].get("doc_type") != doc_type:
                continue
            seen_docs.add(doc_id)
            hits.append(hit)
        for doc_id in doc_ids:
            if doc_id in seen_docs:
                continue
            doc_chunks = self.chunks_by_doc.get(doc_id)
            if not doc_chunks:
                continue
            seen_docs.add(doc_id)
            hits.append({"score": 0.0, "chunk": doc_chunks[0]})
        return hits

    def build_context(
        self,
        query: str,
        k: int = 8,
        use_graph: bool = True,
        compare_types: list[str] | None = None,
        degraded: bool = False,
    ) -> tuple[str, list[dict]]:
        """Retrieval context. The SAME per-type-restricted-search + profile-block
        mechanism applies whether `compare_types` names one type (a descriptive
        question, e.g. "quelles sont les caractéristiques d'un memorandum ?") or
        several (an explicit comparison) -- one shared loop, not a separate code
        path per scenario, so retrieval bugs only need fixing in one place.
        `degraded=True` additionally appends an honest, unrestricted free-text
        search standing in for whatever term(s) in the question didn't match a
        real corpus type (mirrors platform/site/worker/ask.ts's degradedCompare) --
        see build_degraded_notice for how that's disclaimed."""
        blocks: list[str] = []
        seen_docs: set[str] = set()
        seen_chunk_ids: set[str] = set()
        hits: list[dict] = []
        compare_types = compare_types or []

        if degraded:
            blocks.append(build_degraded_notice(compare_types, self.doc_type_profiles))

        if compare_types:
            for label in compare_types:
                profile_block = self.doc_type_profile_block(label)
                if profile_block:
                    blocks.append(profile_block)
                # No cap: every document of this type goes into context, not a
                # fixed top-k sample (see all_hits_for_doc_type docstring).
                type_hits = self.all_hits_for_doc_type(query, label)
                for hit in type_hits:
                    chunk_id = hit["chunk"].get("chunk_id")
                    if chunk_id in seen_chunk_ids:
                        continue
                    seen_chunk_ids.add(chunk_id)
                    hits.append(hit)
                    blocks.append(self.hit_block(hit, use_graph, seen_docs))

        if degraded or not compare_types:
            # Free-text stand-in (degraded mode) or the only retrieval (plain
            # questions naming no known type): plain top-k search over the
            # whole corpus, excluding whatever the type-restricted loop above
            # already picked up.
            free_k = max(3, k - len(hits))
            for hit in self.search(query, k=free_k):
                chunk_id = hit["chunk"].get("chunk_id")
                if chunk_id in seen_chunk_ids:
                    continue
                seen_chunk_ids.add(chunk_id)
                hits.append(hit)
                blocks.append(self.hit_block(hit, use_graph, seen_docs))

        return "\n\n---\n\n".join(blocks), hits


def ask_llm(question: str, context: str, api_url: str, api_model: str, api_key: str, timeout: float = 60) -> str:
    import requests

    payload = {
        "model": api_model,
        "messages": [
            {"role": "system", "content": RAG_SYSTEM_PROMPT},
            {"role": "user", "content": f"Contexte :\n\n{context}\n\n---\n\nQuestion : {question}"},
        ],
        "temperature": 0.2,
    }
    response = requests.post(
        api_url,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


# Mirrors callModel's retry logic in platform/site/worker/ask.ts: a
# comparison/descriptive question over a large named type makes many
# sequential ask_llm calls (see generate_answer's map-reduce path below), so
# one transient failure (network blip, momentary 5xx) shouldn't throw away
# every batch that already succeeded -- retry a couple of times with backoff
# first.
CALL_LLM_MAX_RETRIES = 2
CALL_LLM_RETRY_DELAY_S = 0.6


def ask_llm_with_retry(question: str, context: str, api_url: str, api_model: str, api_key: str) -> str:
    last_error: Exception | None = None
    for attempt in range(CALL_LLM_MAX_RETRIES + 1):
        try:
            return ask_llm(question, context, api_url, api_model, api_key)
        except Exception as exc:  # noqa: BLE001 - retried below, re-raised if exhausted
            last_error = exc
            if attempt < CALL_LLM_MAX_RETRIES:
                time.sleep(CALL_LLM_RETRY_DELAY_S * (attempt + 1))
    assert last_error is not None
    raise last_error


@dataclass
class AnswerResult:
    answer: str
    # True when a map-reduce batch failed even after retries but earlier
    # batches had already succeeded -- the answer is real, but built from
    # fewer documents than the full named type (see generate_answer).
    partial: bool = False
    completed_steps: int = 0
    total_steps: int = 1
    failure_note: str | None = None


# Mirrors MAP_REDUCE_BATCH_SIZE / generateAnswer in platform/site/worker/
# ask.ts. A comparison/descriptive question naming a type retrieves EVERY
# document of that type (no cap -- see KnowledgeBase.build_context /
# all_hits_for_doc_type), which can be hundreds of chunks for a large type.
# Below this many hits, behaviour is unchanged: one ask_llm call with the
# whole context. Above it, split into batches, get concise notes per batch
# (sequential -- avoids concurrent calls tripping OpenCode Zen's free-tier
# rate limiting), then one final call synthesising the batch notes into a
# single answer. Every retrieved document is still used either way.
MAP_REDUCE_BATCH_SIZE = 60


def generate_answer(
    kb: KnowledgeBase,
    query: str,
    compare_types: list[str],
    degraded: bool,
    hits: list[dict],
    use_graph: bool,
    api_url: str,
    api_model: str,
    api_key: str,
) -> AnswerResult:
    profile_blocks = [kb.doc_type_profile_block(label) for label in compare_types]
    profile_blocks = [block for block in profile_blocks if block]
    degraded_notice = build_degraded_notice(compare_types, kb.doc_type_profiles) if degraded and hits else None
    constant_blocks = ([degraded_notice] if degraded_notice else []) + profile_blocks

    if len(hits) <= MAP_REDUCE_BATCH_SIZE:
        seen_docs: set[str] = set()
        blocks = list(constant_blocks)
        blocks += [kb.hit_block(hit, use_graph, seen_docs) for hit in hits]
        answer = ask_llm_with_retry(query, "\n\n---\n\n".join(blocks), api_url, api_model, api_key)
        return AnswerResult(answer=answer, completed_steps=1, total_steps=1)

    batches = [hits[i : i + MAP_REDUCE_BATCH_SIZE] for i in range(0, len(hits), MAP_REDUCE_BATCH_SIZE)]
    total_steps = len(batches) + 1
    partials: list[str] = []
    failure_note: str | None = None
    for i, batch in enumerate(batches, start=1):
        seen_docs = set()
        batch_blocks = list(constant_blocks) + [kb.hit_block(hit, use_graph, seen_docs) for hit in batch]
        batch_question = (
            f"Question originale : {query}\n\n"
            f"Ceci est le lot {i}/{len(batches)} de documents pertinents pour cette question. Ne réponds PAS de "
            "façon définitive et n'invente rien au-delà de ce lot : extrais uniquement, sous forme de notes "
            "concises, les faits et citations [document_id] de CE lot utiles pour répondre à la question plus "
            "tard."
        )
        try:
            partial = ask_llm_with_retry(batch_question, "\n\n---\n\n".join(batch_blocks), api_url, api_model, api_key)
        except Exception as exc:  # noqa: BLE001 - handled below, real progress is preserved either way
            failure_note = f"échec au lot {i}/{len(batches)} ({exc})"
            break
        partials.append(f"### Notes du lot {i}/{len(batches)}\n\n{partial}")

    if failure_note:
        if not partials:
            # Nothing succeeded at all -- genuinely no partial progress to
            # preserve, so this is a real failure, not a partial success.
            raise RuntimeError(f"{failure_note} -- aucun lot n'a pu être traité, aucune donnée partielle disponible.")
        partial_notice = (
            "### Réponse partielle\n\n"
            f"Une erreur est survenue en cours de traitement ({failure_note}). Cette réponse se base uniquement "
            f"sur les {len(partials)}/{len(batches)} lots traités avec succès avant l'erreur -- elle ne couvre "
            "pas l'ensemble des documents du type demandé. Indique clairement cette limite dans ta réponse."
        )
        reduce_question = (
            f"Question : {query}\n\n"
            f"Voici des notes préparées à partir de SEULEMENT {len(partials)}/{len(batches)} lots de documents "
            "(le reste a échoué -- voir la note de réponse partielle). Synthétise ces notes en UNE réponse "
            "cohérente, en conservant les citations [document_id] déjà présentes, et en rappelant explicitement "
            "que la réponse est partielle."
        )
        reduce_context = "\n\n---\n\n".join([*constant_blocks, partial_notice, *partials])
        try:
            answer = ask_llm_with_retry(reduce_question, reduce_context, api_url, api_model, api_key)
        except Exception:  # noqa: BLE001 - fall back to raw notes below
            answer = f"{partial_notice}\n\n" + "\n\n".join(partials)
        return AnswerResult(
            answer=answer,
            partial=True,
            completed_steps=len(partials),
            total_steps=total_steps,
            failure_note=failure_note,
        )

    reduce_question = (
        f"Question : {query}\n\n"
        f"Voici des notes préparées à partir de {len(hits)} documents du corpus, en {len(batches)} lots. "
        "Synthétise-les en UNE réponse finale cohérente et complète, en conservant les citations [document_id] "
        "déjà présentes dans les notes plutôt qu'en les supprimant."
    )
    reduce_context = "\n\n---\n\n".join(list(constant_blocks) + partials)
    answer = ask_llm_with_retry(reduce_question, reduce_context, api_url, api_model, api_key)
    return AnswerResult(answer=answer, completed_steps=total_steps, total_steps=total_steps)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("query", nargs="?", help="Question. Omit for interactive mode.")
    parser.add_argument(
        "--k",
        type=int,
        default=12,
        help="Number of chunks to retrieve (for a comparison question naming N types, "
        "this is treated as a shared budget split across types, min 3/type -- see build_context).",
    )
    parser.add_argument("--no-graph", action="store_true", help="Disable knowledge-graph context expansion.")
    parser.add_argument("--no-llm", action="store_true", help="Print retrieved context only, skip the LLM call.")
    parser.add_argument("--api-url", default=os.environ.get("RAG_API_URL", DEFAULT_API_URL))
    parser.add_argument("--api-model", default=os.environ.get("RAG_API_MODEL", DEFAULT_API_MODEL))
    parser.add_argument("--similarity-dir", type=Path, default=DEFAULT_SIMILARITY_DIR)
    parser.add_argument("--release-dir", type=Path, default=DEFAULT_RELEASE_DIR)
    parser.add_argument("--graph-dir", type=Path, default=DEFAULT_GRAPH_DIR)
    parser.add_argument(
        "--doc-type-profiles",
        type=Path,
        default=None,
        help="Path to doc_type_profiles.json (default: <similarity-dir>/doc_type_profiles.json).",
    )
    parser.add_argument(
        "--no-compare-mode", action="store_true", help="Disable doc_type comparison-question detection."
    )
    return parser.parse_args()


def _detect_compare_types(question: str, args: argparse.Namespace, kb: KnowledgeBase) -> list[str]:
    compare_types = [] if args.no_compare_mode else kb.detect_comparison_types(question)
    if len(compare_types) >= 2:
        print(f"[mode comparaison de types activé : {', '.join(compare_types)}]", file=sys.stderr)
    elif len(compare_types) == 1:
        print(f"[type reconnu dans la question : {compare_types[0]}]", file=sys.stderr)
    return compare_types


def _print_answer(
    kb: KnowledgeBase,
    question: str,
    compare_types: list[str],
    degraded: bool,
    hits: list,
    args: argparse.Namespace,
    api_key: str,
) -> None:
    try:
        result = generate_answer(
            kb, question, compare_types, degraded, hits, not args.no_graph, args.api_url, args.api_model, api_key
        )
    except Exception as exc:  # noqa: BLE001 - report and fall back, don't crash a REPL
        print(f"Échec de l'appel LLM ({exc}) — affichage du contexte brut à la place.", file=sys.stderr)
        return
    if result.partial:
        print(
            f"[réponse partielle : {result.completed_steps}/{result.total_steps} étapes traitées avant "
            f"l'erreur -- {result.failure_note}]",
            file=sys.stderr,
        )
    print(result.answer)
    print("\nSources :", file=sys.stderr)
    for hit in hits:
        chunk = hit["chunk"]
        print(f"  - [{chunk['document_id']}] p.{chunk.get('page_number')} (score {hit['score']:.2f})", file=sys.stderr)


def _handle_question(question: str, args: argparse.Namespace, kb: KnowledgeBase) -> None:
    compare_types = _detect_compare_types(question, args, kb)
    # A comparison-shaped question with fewer than 2 real doc_types matched
    # used to hard-refuse via unmatched_type_clarification. It now falls
    # through to the same type-aware build_context instead, with
    # degraded=True adding an honest free-text stand-in for the unmatched
    # term(s) -- see build_context's docstring.
    degraded = not args.no_compare_mode and len(compare_types) < 2 and has_comparison_intent(question)
    context, hits = kb.build_context(
        question, k=args.k, use_graph=not args.no_graph, compare_types=compare_types, degraded=degraded
    )
    if degraded:
        if not hits:
            clarification = unmatched_type_clarification(question, compare_types, kb.doc_type_profiles)
            print(
                clarification
                or "Aucun document du corpus ne semble correspondre à cette question. Essayez une autre formulation."
            )
            return
        print("[mode comparaison dégradée : recherche libre pour le(s) terme(s) non reconnu(s)]", file=sys.stderr)
    print(f"[{len(hits)} extraits récupérés]", file=sys.stderr)

    if args.no_llm:
        print(context)
        return

    api_key = os.environ.get("OPENCODE_API_KEY")
    if not api_key:
        print(
            "OPENCODE_API_KEY n'est pas défini (voir l'en-tête de scripts/rag_ask.py) — "
            "affichage du contexte brut uniquement.",
            file=sys.stderr,
        )
        print(context)
        return

    _print_answer(kb, question, compare_types, degraded, hits, args, api_key)


def main() -> int:
    args = parse_args()
    profiles_path = args.doc_type_profiles or (args.similarity_dir / "doc_type_profiles.json")
    kb = KnowledgeBase(args.similarity_dir, args.release_dir, args.graph_dir, doc_type_profiles_path=profiles_path)

    if args.query:
        _handle_question(args.query, args, kb)
        return 0

    print("Mode interactif — Ctrl+D ou 'exit' pour quitter.", file=sys.stderr)
    while True:
        try:
            question = input("\n> ").strip()
        except EOFError:
            break
        if not question or question.lower() in {"exit", "quit"}:
            break
        _handle_question(question, args, kb)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
