#!/usr/bin/env python3
"""Local retrieval-augmented question answering over the Lexis Mollis corpus.

Retrieval is entirely local and free: it reuses the embeddings/FAISS index
already built by `pdfkb similarity build` (sentence-transformers/LaBSE,
no API calls) plus the knowledge graph already built by `pdfkb graph build`
to pull in related documents and entities for each retrieved passage. Only
the final answer is generated by an LLM — by default the free "Big Pickle"
model on OpenCode Zen (https://opencode.ai/zen/), an OpenAI-compatible API.
Run `curl https://opencode.ai/zen/v1/models` for the current list of free
("-free" suffixed) and paid model ids.

Setup for the LLM step (skip with --no-llm to only use retrieval, for free
with no account at all):
  1. Sign in at https://opencode.ai/zen/ and copy an API key. Note the docs
     ask for billing details even to use free models — check current terms
     before proceeding, this script never touches payment info itself.
  2. export OPENCODE_API_KEY=...
Any other OpenAI-compatible endpoint works too via --api-url/--api-model
(or RAG_API_URL/RAG_API_MODEL env vars), e.g. a local Ollama server.

Comparison questions ("compare les types de documents (traité, accord,
déclaration) et dis-moi s'il y a des différences de forme/rédaction") are
detected automatically: if a question names two or more known `doc_type`
labels, the context is built differently from a plain question — it is
prepended with the corpus-wide structural profile of each named type
(`outputs_v2/similarity/doc_type_profiles.json`, built by `pdfkb similarity
build` / `scripts/build_doc_type_profiles.py`: fraction of documents with a
"pleins pouvoirs" preamble, numbered articles, "En foi de quoi" signature
clause, etc.) plus a few real excerpts retrieved *per type* rather than one
undifferentiated top-k search — see `KnowledgeBase.detect_comparison_types`
and `KnowledgeBase.build_context`. This is what lets a small free model
answer precisely instead of guessing from 6-8 semantically-nearest chunks
that may all happen to come from the same type.

Examples:
  .venv/bin/python scripts/rag_ask.py "Quels traités mentionnent la Roumanie ?"
  .venv/bin/python scripts/rag_ask.py "Compare les types de documents (traité, accord, déclaration) et dis-moi s'il y a des différences de forme/rédaction"
  .venv/bin/python scripts/rag_ask.py --no-llm "citoyenneté"   # retrieval only
  .venv/bin/python scripts/rag_ask.py                          # interactive
"""

from __future__ import annotations

import os

# Must be set before faiss/torch touch OpenMP: on macOS, faiss's and
# sentence-transformers' (torch) bundled OpenMP runtimes are two separate
# copies, which OpenMP aborts on by default. This is the documented,
# widely-used (if "unsupported") workaround; combined with pinning faiss to
# one thread below, it's stable in practice.
os.environ.setdefault("KMP_DUPLICATE_LIB_OK", "TRUE")
os.environ.setdefault("OMP_NUM_THREADS", "1")

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from pdfkb.similarity.doc_type_profiles import load_doc_type_mapping  # noqa: E402
from pdfkb.similarity.io import read_parquet_records  # noqa: E402
from pdfkb.similarity.lexical import normalise_lexical  # noqa: E402

DEFAULT_SIMILARITY_DIR = Path("outputs_v2/similarity")
DEFAULT_RELEASE_DIR = Path("outputs_v2/release")
DEFAULT_GRAPH_DIR = Path("outputs_v2/graph")
DEFAULT_DOC_TYPE_MAPPING = Path("metadata_design/doc_type_mapping.json")
DEFAULT_EMBEDDING_MODEL = "sentence-transformers/LaBSE"
DEFAULT_API_URL = "https://opencode.ai/zen/v1/chat/completions"
DEFAULT_API_MODEL = "big-pickle"
DOC_EDGE_TYPES = {"similar_to", "translation", "same_instrument_as"}

SYSTEM_PROMPT = (
    "Tu es un assistant de recherche qui répond STRICTEMENT à partir des extraits de documents "
    "fournis (corpus de traités et instruments juridiques Lexis Mollis, OCR historique, parfois "
    "imparfait). Si l'information n'est pas dans le contexte fourni, dis-le clairement plutôt que "
    "d'inventer. Cite systématiquement l'identifiant de document entre crochets (ex. [16460004_s1]) "
    "et la page quand c'est pertinent. Réponds dans la langue de la question. Si le contexte contient "
    "des sections « Profil du type documentaire », base toute comparaison de forme/rédaction entre "
    "types de documents sur les statistiques qu'elles donnent (fractions de documents, moyennes) et "
    "cite les pourcentages exacts plutôt que des impressions générales ; illustre avec les extraits "
    "réels fournis."
)


def _label_variants(label: str) -> set[str]:
    """Normalised singular/plural forms of a doc_type label for substring matching
    against a normalised question (see `normalise_lexical`: lowercase, no accents,
    punctuation collapsed to single spaces)."""
    norm = normalise_lexical(label)
    if not norm:
        return set()
    variants = {norm}
    words = norm.split()
    if not norm.endswith("s"):
        variants.add(norm + "s")
    if len(words) > 1 and not words[-1].endswith("s"):
        variants.add(" ".join(words[:-1] + [words[-1] + "s"]))
    return variants


def detect_doc_types(query: str, labels: list[str]) -> list[str]:
    """Return the known doc_type labels named in `query` (order-preserving, no dupes)."""
    padded_query = f" {normalise_lexical(query)} "
    matched: list[str] = []
    for label in labels:
        if any(f" {variant} " in padded_query for variant in _label_variants(label)):
            matched.append(label)
    return matched


def _normalise(vectors: np.ndarray) -> np.ndarray:
    vectors = np.asarray(vectors, dtype=np.float32)
    if vectors.ndim == 1:
        vectors = vectors.reshape(1, -1)
    norms = np.linalg.norm(vectors, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return vectors / norms


class KnowledgeBase:
    """In-memory view over the already-built similarity index and graph."""

    def __init__(
        self,
        similarity_dir: Path = DEFAULT_SIMILARITY_DIR,
        release_dir: Path = DEFAULT_RELEASE_DIR,
        graph_dir: Path = DEFAULT_GRAPH_DIR,
        embedding_model: str = DEFAULT_EMBEDDING_MODEL,
        doc_type_profiles_path: Path = DEFAULT_SIMILARITY_DIR / "doc_type_profiles.json",
        doc_type_mapping_path: Path = DEFAULT_DOC_TYPE_MAPPING,
    ) -> None:
        import faiss

        # faiss's and torch's bundled OpenMP runtimes crash (segfault) if faiss
        # is left multi-threaded in the same process as sentence-transformers
        # on macOS — pin faiss to one thread rather than relying on env vars
        # the caller might not have set.
        faiss.omp_set_num_threads(1)

        self.embedding_model_name = embedding_model
        self._model: Any = None

        self.index = faiss.read_index(str(Path(similarity_dir) / "faiss.index"))
        id_map = read_parquet_records(Path(similarity_dir) / "id_map.parquet")
        self.row_to_chunk_id = {int(row["row_index"]): row["chunk_id"] for row in id_map}

        self.chunks_by_id = {c["chunk_id"]: c for c in read_parquet_records(Path(release_dir) / "chunks")}
        self.documents_by_id = {d["document_id"]: d for d in read_parquet_records(Path(release_dir) / "documents")}

        self.doc_edges: dict[str, list[dict]] = defaultdict(list)
        for edge in read_parquet_records(Path(release_dir) / "edges"):
            if (
                edge.get("level") == "document"
                and edge.get("type") in DOC_EDGE_TYPES
                and str(edge.get("src", "")).startswith("doc:")
                and str(edge.get("dst", "")).startswith("doc:")
            ):
                self.doc_edges[edge["src"]].append(edge)

        self.mentions_by_doc: dict[str, list[dict]] = defaultdict(list)
        for mention in read_parquet_records(Path(graph_dir) / "mention_links.parquet"):
            self.mentions_by_doc[mention["document_id"]].append(mention)
        self.nodes_by_id = {n["node_id"]: n for n in read_parquet_records(Path(graph_dir) / "nodes.parquet")}

        # Optional: doc_type structural profiles (see pdfkb/similarity/doc_type_profiles.py).
        # Absent on older builds — comparison-mode retrieval degrades gracefully to plain
        # top-k search in that case (see `detect_comparison_types`/`build_context`).
        self.doc_type_profiles: dict[str, Any] = {}
        profiles_path = Path(doc_type_profiles_path)
        if profiles_path.exists():
            self.doc_type_profiles = json.loads(profiles_path.read_text(encoding="utf-8")).get("types", {})
        self.doc_type_labels = sorted(load_doc_type_mapping(Path(doc_type_mapping_path)).keys()) or sorted(
            self.doc_type_profiles.keys()
        )

    def _embed_query(self, text: str) -> np.ndarray:
        if self._model is None:
            from sentence_transformers import SentenceTransformer

            self._model = SentenceTransformer(self.embedding_model_name)
        vector = self._model.encode([text], normalize_embeddings=True)
        return _normalise(np.asarray(vector, dtype=np.float32))

    def search(self, query: str, k: int = 8) -> list[dict]:
        query_vector = self._embed_query(query)
        scores, indices = self.index.search(query_vector, k)
        hits = []
        for score, row in zip(scores[0], indices[0], strict=True):
            if row < 0:
                continue
            chunk = self.chunks_by_id.get(self.row_to_chunk_id.get(int(row)))
            if chunk is not None:
                hits.append({"score": float(score), "chunk": chunk})
        return hits

    def entities_for_document(self, document_id: str, limit: int = 6) -> list[dict]:
        rows = sorted(self.mentions_by_doc.get(document_id, []), key=lambda r: r.get("confidence") or 0, reverse=True)
        seen: dict[str, dict] = {}
        for mention in rows:
            node = self.nodes_by_id.get(mention["node_id"])
            if node is None or node["node_id"] in seen:
                continue
            seen[node["node_id"]] = node
            if len(seen) >= limit:
                break
        return list(seen.values())

    def related_documents(self, document_id: str, limit: int = 4) -> list[dict]:
        edges = sorted(
            self.doc_edges.get(f"doc:{document_id}", []),
            key=lambda e: e.get("combined") or e.get("quality_weight") or 0,
            reverse=True,
        )
        related, seen = [], set()
        for edge in edges:
            dst_id = str(edge["dst"])[len("doc:") :]
            if dst_id in seen or dst_id == document_id:
                continue
            seen.add(dst_id)
            doc = self.documents_by_id.get(dst_id)
            if doc is not None:
                related.append({"document": doc, "type": edge["type"], "score": edge.get("combined") or edge.get("quality_weight")})
            if len(related) >= limit:
                break
        return related

    def detect_comparison_types(self, query: str) -> list[str]:
        """Doc_type labels named in `query`, restricted to types we have profiles for.
        Comparison mode (see `build_context`) only activates with >=2 matches — a
        question naming a single type is answered fine by plain top-k retrieval."""
        matched = detect_doc_types(query, self.doc_type_labels)
        return [label for label in matched if label in self.doc_type_profiles] or matched

    def doc_type_profile_block(self, label: str) -> str | None:
        profile = self.doc_type_profiles.get(label)
        if not profile:
            return None
        lines = [
            f"### Profil du type documentaire « {label} » "
            f"({profile.get('instrument_type', 'n/a')}, force juridique={profile.get('legal_force', 'n/a')})",
            profile.get("narrative_fr") or "",
        ]
        openings = profile.get("sample_openings") or []
        if openings:
            lines += ["", "Exemples réels (débuts de document) :"]
            for sample in openings[:3]:
                lines.append(f"- [{sample.get('document_id')}] ({sample.get('year') or 'n/a'}) : « {sample.get('excerpt')} »")
        return "\n".join(lines)

    def _hit_block(self, hit: dict, use_graph: bool, seen_docs: set[str]) -> str:
        chunk = hit["chunk"]
        doc = self.documents_by_id.get(chunk["document_id"], {})
        lines = [
            f"### [{chunk['document_id']}] {chunk.get('title') or doc.get('title') or chunk['document_id']} "
            f"(p.{chunk.get('page_number')}, score={hit['score']:.2f})",
            f"Traité : {chunk.get('treaty_id') or 'n/a'} · Année : {chunk.get('year') or 'n/a'} · "
            f"Type : {chunk.get('doc_type') or 'n/a'}",
            "",
            (chunk.get("text") or "").strip(),
        ]
        if use_graph and chunk["document_id"] not in seen_docs:
            seen_docs.add(chunk["document_id"])
            entities = self.entities_for_document(chunk["document_id"])
            if entities:
                lines += ["", "Entités liées : " + ", ".join(f"{n['label']} ({n['type']})" for n in entities)]
            related = self.related_documents(chunk["document_id"])
            if related:
                rel_str = "; ".join(
                    f"{r['document'].get('title') or r['document']['document_id']} "
                    f"[{r['document']['document_id']}] ({r['type']})"
                    for r in related
                )
                lines += [f"Documents liés : {rel_str}"]
        return "\n".join(lines)

    def search_by_doc_type(self, query: str, doc_type: str, k: int, pool_k: int = 150) -> list[dict]:
        """Like `search`, but restricted to chunks whose `doc_type` matches — a plain
        top-k search over the whole corpus can easily miss an under-represented type
        entirely (e.g. 152 « Déclaration » docs vs 807 « Autre »), which is exactly
        wrong for a question that asks to compare types."""
        pool = self.search(query, k=max(pool_k, k))
        matching = [hit for hit in pool if hit["chunk"].get("doc_type") == doc_type]
        return matching[:k]

    def build_context(
        self,
        query: str,
        k: int = 8,
        use_graph: bool = True,
        compare_types: list[str] | None = None,
    ) -> tuple[str, list[dict]]:
        blocks: list[str] = []
        seen_docs: set[str] = set()
        hits: list[dict] = []

        if compare_types and len(compare_types) >= 2:
            for label in compare_types:
                profile_block = self.doc_type_profile_block(label)
                if profile_block:
                    blocks.append(profile_block)
            per_type_k = max(2, k // len(compare_types))
            seen_chunk_ids: set[str] = set()
            for label in compare_types:
                for hit in self.search_by_doc_type(query, label, k=per_type_k):
                    chunk_id = hit["chunk"].get("chunk_id")
                    if chunk_id in seen_chunk_ids:
                        continue
                    seen_chunk_ids.add(chunk_id)
                    hits.append(hit)
                    blocks.append(self._hit_block(hit, use_graph, seen_docs))
        else:
            hits = self.search(query, k=k)
            for hit in hits:
                blocks.append(self._hit_block(hit, use_graph, seen_docs))

        return "\n\n---\n\n".join(blocks), hits


def ask_llm(question: str, context: str, api_url: str, api_model: str, api_key: str, timeout: float = 60) -> str:
    import requests

    payload = {
        "model": api_model,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Contexte :\n\n{context}\n\n---\n\nQuestion : {question}"},
        ],
        "temperature": 0.2,
    }
    response = requests.post(
        api_url,
        headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
        json=payload,
        timeout=timeout,
    )
    response.raise_for_status()
    return response.json()["choices"][0]["message"]["content"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("query", nargs="?", help="Question. Omit for interactive mode.")
    parser.add_argument("--k", type=int, default=8, help="Number of chunks to retrieve.")
    parser.add_argument("--no-graph", action="store_true", help="Disable knowledge-graph context expansion.")
    parser.add_argument("--no-llm", action="store_true", help="Print retrieved context only, skip the LLM call.")
    parser.add_argument("--api-url", default=os.environ.get("RAG_API_URL", DEFAULT_API_URL))
    parser.add_argument("--api-model", default=os.environ.get("RAG_API_MODEL", DEFAULT_API_MODEL))
    parser.add_argument("--similarity-dir", type=Path, default=DEFAULT_SIMILARITY_DIR)
    parser.add_argument("--release-dir", type=Path, default=DEFAULT_RELEASE_DIR)
    parser.add_argument("--graph-dir", type=Path, default=DEFAULT_GRAPH_DIR)
    parser.add_argument(
        "--doc-type-profiles",
        type=Path,
        default=None,
        help="Path to doc_type_profiles.json (default: <similarity-dir>/doc_type_profiles.json).",
    )
    parser.add_argument("--no-compare-mode", action="store_true", help="Disable doc_type comparison-question detection.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    profiles_path = args.doc_type_profiles or (args.similarity_dir / "doc_type_profiles.json")
    kb = KnowledgeBase(args.similarity_dir, args.release_dir, args.graph_dir, doc_type_profiles_path=profiles_path)

    def handle(question: str) -> None:
        compare_types = None if args.no_compare_mode else kb.detect_comparison_types(question)
        if compare_types and len(compare_types) >= 2:
            print(f"[mode comparaison de types activé : {', '.join(compare_types)}]", file=sys.stderr)
        context, hits = kb.build_context(question, k=args.k, use_graph=not args.no_graph, compare_types=compare_types)
        print(f"[{len(hits)} extraits récupérés]", file=sys.stderr)

        if args.no_llm:
            print(context)
            return

        api_key = os.environ.get("OPENCODE_API_KEY")
        if not api_key:
            print(
                "OPENCODE_API_KEY n'est pas défini (voir l'en-tête de scripts/rag_ask.py) — "
                "affichage du contexte brut uniquement.",
                file=sys.stderr,
            )
            print(context)
            return

        try:
            answer = ask_llm(question, context, args.api_url, args.api_model, api_key)
        except Exception as exc:  # noqa: BLE001 - report and fall back, don't crash a REPL
            print(f"Échec de l'appel LLM ({exc}) — affichage du contexte brut à la place.", file=sys.stderr)
            print(context)
            return
        print(answer)
        print("\nSources :", file=sys.stderr)
        for hit in hits:
            chunk = hit["chunk"]
            print(f"  - [{chunk['document_id']}] p.{chunk.get('page_number')} (score {hit['score']:.2f})", file=sys.stderr)

    if args.query:
        handle(args.query)
        return 0

    print("Mode interactif — Ctrl+D ou 'exit' pour quitter.", file=sys.stderr)
    while True:
        try:
            question = input("\n> ").strip()
        except EOFError:
            break
        if not question or question.lower() in {"exit", "quit"}:
            break
        handle(question)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
